version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8081:3306"  # Mappa la porta 3306 del container alla porta 8081 del sistema
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 50
    restart: always 

  server:
    build: ./server
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: always  # Aggiungi questa linea

  datacollector:
    build: ./datacollector
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: always  

networks:
  backend:
    driver: bridge

volumes:
  db_data: