
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsystem
  labels:
    app: alertsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertsystem
  template:
    metadata:
      labels:
        app: alertsystem
    spec:
      containers:
      - name: alertsystem
        image: docker.io/library/my_alertsystem_image:latest
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8001