apiVersion: v1
kind: Service
metadata:
  name: datacollector
spec:
  selector:
    app: datacollector
  ports:
    - protocol: TCP
      port: 8000  # Porta per le metriche Prometheus
      targetPort: 8000
  type: ClusterIP