apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: user-command-service
        image: docker.io/library/user-command-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
      - name: user-query-service
        image: docker.io/library/user-query-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"