apiVersion: v1
kind: Service
metadata:
  name: alertnotificationsystem-service
spec:
  selector:
    app: alertnotificationsystem
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer